ALTER TABLE search_cycle_stats
  ADD COLUMN IF NOT EXISTS wrong_model  INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS year_out     INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS price_out    INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS km_over      INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hand_over    INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS other_filter INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS score_min    REAL,
  ADD COLUMN IF NOT EXISTS score_max    REAL,
  ADD COLUMN IF NOT EXISTS score_avg    REAL,
  ADD COLUMN IF NOT EXISTS price_min    INT,
  ADD COLUMN IF NOT EXISTS price_max    INT;
