ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS sub_model TEXT NOT NULL DEFAULT '';
ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS engine_volume DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS horse_power INTEGER NOT NULL DEFAULT 0;
ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS engine_type TEXT NOT NULL DEFAULT '';
ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS gear_box TEXT NOT NULL DEFAULT '';
ALTER TABLE listing_history ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
